---
# handlers file for nginx
    - name: nginx start
      service: name=nginx state=started
    - name: nginx restart
      service: name=nginx state=restarted
    - name: nginx set enabled
      service: name=nginx enabled=yes

