---
# vars file for myserver
sysctl_settings: 
  - name: net.core.somaxconn
    value: 1024
  - name: net.core.rmem_max
    value: 8388608
  - name: net.core.wmem_max
    value: 8388608
  - name: net.core.rmem_default
    value: 65536
  - name: net.core.wmem_default
    value: 65536
  - name: net.ipv4.tcp_rmem
    value: '4096 87380 8388608'
  - name: net.ipv4.tcp_wmem
    value: '4096 65536 8388608'
  - name: net.ipv4.tcp_mem
    value: '8388608 8388608 8388608'

