#!/bin/bash
#
# Print names and values of all uppercase variables
#
allLetters=`echo {A..Z}`
letters=${1-$allLetters}
for l in $letters;
do
	# Get all varnames starting with some letter $l
	eval vars='${!'$l'*}'
	# If we found at least one var - iterate through them
	if [ -n "$vars" ] 
	then
		for var in $vars;
		do
			# get value of var
			eval 'val=$'${var}
			# print var name and value
			echo "${var}=${val}"
		done
	fi
done
